# Generated by Django 3.0.7 on 2022-12-21 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutuSumu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutu_wa_sumu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nambala_ya_sumu', models.IntegerField(default=0)),
                ('zina_la_sumu', models.CharField(max_length=255)),
                ('mlembi', models.CharField(default='', max_length=255)),
                ('mutu_sumu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumu.MutuSumu')),
            ],
        ),
        migrations.CreateModel(
            name='Mizere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nambala', models.IntegerField(default=0)),
                ('mizere', models.TextField()),
                ('mutu_sumu_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sumu.MutuSumu')),
                ('zina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sumu.Zina')),
            ],
        ),
    ]
