# Generated by Django 2.0.2 on 2022-12-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dzina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzina_la_nyimbo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mizere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mizere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MutuNyimbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutu_wa_nyimbo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MutuSumu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutu_wa_sumu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ndime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndime', models.TextField()),
                ('dzina_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Dzina')),
            ],
        ),
        migrations.CreateModel(
            name='Stanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanza', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=255)),
                ('header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Header')),
            ],
        ),
        migrations.CreateModel(
            name='Zina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zina_la_sumu', models.CharField(max_length=255)),
                ('mutu_sumu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuSumu')),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='hearder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Title'),
        ),
        migrations.AddField(
            model_name='zina',
            name='mutu_sumu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Zina'),
        ),
        migrations.AddField(
            model_name='dzina',
            name='mutu_nyimbo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuNyimbo'),
        ),
        migrations.AddField(
            model_name='stanza',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Title'),
        ),
        migrations.AddField(
            model_name='mizere',
            name='zina_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.Zina'),
        ),
        migrations.AddField(
            model_name='dzina',
            name='mutu_nyimbo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuNyimbo'),
        ),
    ]
