# Generated by Django 2.0.2 on 2022-12-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanza',
            old_name='stanza',
            new_name='stanza_text',
        ),
        migrations.RemoveField(
            model_name='title',
            name='hearder_id',
        ),
        migrations.AddField(
            model_name='mizere',
            name='nambala',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ndime',
            name='nambara',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stanza',
            name='stanza_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zina',
            name='mutu_sumu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuSumu'),
        ),
    ]
