# Generated by Django 2.0.2 on 2022-12-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0004_auto_20221216_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='mizere',
            name='mutu_sumu_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuSumu'),
        ),
        migrations.AddField(
            model_name='ndime',
            name='mutu_nyimbo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hymns.MutuNyimbo'),
        ),
        migrations.AddField(
            model_name='stanza',
            name='header_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hymns.Header'),
        ),
    ]
