# Generated by Django 3.0.7 on 2022-12-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0005_auto_20221216_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mizere',
            name='mutu_sumu_id',
        ),
        migrations.RemoveField(
            model_name='mizere',
            name='zina_id',
        ),
        migrations.RemoveField(
            model_name='ndime',
            name='dzina_id',
        ),
        migrations.RemoveField(
            model_name='ndime',
            name='mutu_nyimbo_id',
        ),
        migrations.RemoveField(
            model_name='zina',
            name='mutu_sumu_id',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='auther',
            new_name='author',
        ),
        migrations.DeleteModel(
            name='Dzina',
        ),
        migrations.DeleteModel(
            name='Mizere',
        ),
        migrations.DeleteModel(
            name='MutuNyimbo',
        ),
        migrations.DeleteModel(
            name='MutuSumu',
        ),
        migrations.DeleteModel(
            name='Ndime',
        ),
        migrations.DeleteModel(
            name='Zina',
        ),
    ]
